services:
  yeesite-controller:
    build: .
    container_name: yeesite-controller
    restart: unless-stopped
    ports:
      - "5003:5003"
    environment:
      - OLA_HOST=10.0.0.10
      - OLA_PORT=9090
      - DMX_UNIVERSE=1
      - WEB_PORT=5003
    network_mode: bridge
