enabled = true
always_broadcast = false
ip = 10.0.15.109
long_name = OLA Art-Net Node
short_name = OLA
subnet = 0
universe = 0
input_ports = 1
net = 0
output_ports = 4
use_limited_broadcast = false
use_loopback = false